const countries = [ "ad", "ae", "af", "ag", "al", "am", "ao", "ar",
                    "at", "au", "az", "ba", "bb", "bd", "be", "bf",
                    "bg", "bh", "bi", "bj", "bn", "bo", "br", "bs",
                    "bt", "bw", "by", "bz", "ca", "cd", "cf", "cg",
                    "ch", "ci", "cl", "cm", "cn", "co", "cr", "cu",
                    "cv", "cw", "cy", "cz", "de", "dj", "dk", "dm",
                    "do", "dz", "ec", "ee", "eg", "er", "es", "et",
                    "fi", "fj", "fm", "fr", "ga", "gb", "gd", "ge",
                    "gf", "gg", "gh", "gm", "gn", "gq", "gr", "gt",
                    "gw", "gy", "hn", "hr", "ht", "hu", "id", "ie",
                    "is", "in", "iq", "ir", "is", "it", "jm", "jo",
                    "jp", "ke", "kg", "kh", "ki", "km", "kn", "kp",
                    "kr", "kw", "kz", "la", "lb", "lc", "li", "lk",
                    "lr", "ls", "lt", "lu", "lv", "ly", "ma", "mc",
                    "md", "me", "mg", "mh", "mk", "ml", "mm", "mn",
                    "mr", "mt", "mu", "mv", "mw", "mx", "my", "mz",
                    "na", "ne", "ng", "ni", "nl", "no", "np", "nr",
                    "nz", "om", "pa", "pe", "pg", "ph", "pk", "pl",
                    "ps", "pt", "pw", "py", "qa", "ro", "rs", "ru",
                    "rw", "sa", "sb", "sc", "sd", "se", "sg", "si",
                    "sk", "sl", "sm", "sn", "so", "sr", "ss", "st",
                    "sv", "sy", "sz", "td", "tg", "th", "tj", "tm",
                    "tn", "to", "tr", "tt", "tv", "tw", "tz", "ua",
                    "ug", "us", "uy", "uz", "va", "vc", "ve", "vn",
                    "vu", "ws", "xk", "ye", "za", "zm", "zw" ];

const countriesV2 = [
  ["ad", "andorra"],
  ["ae", "united arab emirates", "de forente arabiske emirater", "uae", "forente arabiske emirater", "fae"],
  ["af", "afghanistan"],
  ["ag", "antigua and barbuda", "antigua og barbuda", "antigua", "barbuda", "waladli"],
  ["al", "albania"],
  ["am", "armenia"],
  ["ao", "angola"],
  ["ar", "argentina"],
  ["at", "austria", "østerriket"],
  ["au", "australia"],
  ["az", "azerbaijan", "aserbajdsjan"],
  ["ba", "bosnia and herzegovina", "bosnia", "herzegovina"],
  ["bb", "barbados"],
  ["bd", "bangladesh"],
  ["be", "belgium", "belgia"],
  ["bf", "burkina faso"],
  ["bg", "bulgaria"],
  ["bh", "bahrain"],
  ["bi", "burundi"],
  ["bj", "benin"],
  ["bn", "brunei"],
  ["bo", "bolivia"],
  ["br", "brazil", "brasil"],
  ["bs", "bahamas"],
  ["bt", "bhutan"],
  ["bw", "botswana"],
  ["by", "belarus", "hviterussland"],
  ["bz", "belize"],
  ["ca", "canada"],
  ["cd", "democratic republic of congo", "den demokratiske republikken kongo", "drc", "drk"],
  ["cf", "central african republic", "den sentralafrikanske republikk", "car", "sar"],
  ["cg", "congo", "kongo", "republic of congo", "republikken kongo"],
  ["ch", "switzerland", "sveits"],
  ["ci", "ivory coast", "elfenbenkysten", "ivorycoast"],
  ["cl", "chile"],
  ["cm", "cameroon", "kamerun"],
  ["cn", "china", "kina"],
  ["co", "colombia"],
  ["cr", "costa rica"],
  ["cu", "cuba"],
  ["cv", "cape verde", "kapp verde"],
  ["cy", "cyprus", "kypros"],
  ["cz", "czech republic", "tsjekkia", "czechia"],
  ["de", "germany", "tyskland"],
  ["dj", "djibouti"],
  ["dk", "denmark", "danmark"],
  ["dm", "dominica"],
  ["do", "dominican republic", "den dominikanske republikk", "dominikanske republikk"],
  ["dz", "algeria", "algerie"],
  ["ec", "ecuador"],
  ["ee", "estonia", "estland"],
  ["eg", "egypt"],
  ["er", "eritrea"],
  ["es", "spain", "spania"],
  ["et", "ethiopia", "etiopia"],
  ["fi", "finland"],
  ["fj", "fiji"],
  ["fm", "federated states of micronesia", "mikronesiaføderasjonen", "micronesia", "mikronesia"],
  ["fr", "france", "frankrike"],
  ["ga", "gabon"],
  ["gb", "united kingdom", "storbritannia", "uk", "gb", "great britain"],
  ["gd", "grenada"],
  ["ge", "georgia"],
  ["gh", "ghana"],
  ["gm", "gambia"],
  ["gn", "guinea"],
  ["gq", "equatorial guinea", "ekvatorial-guinea", "ekvatorial guinea"],
  ["gr", "greece", "hellas"],
  ["gt", "guatemala"],
  ["gw", "guinea-bissau"],
  ["gy", "guyana"],
  ["hn", "honduras"],
  ["hr", "croatia", "kroatia"],
  ["ht", "haiti"],
  ["hu", "hungary", "ungarn"],
  ["id", "indonesia"],
  ["ie", "ireland", "irland"],
  ["il", "israel"],
  ["in", "india"],
  ["iq", "iraq", "irak"],
  ["ir", "islamic republic of iran", "den islamske republikk iran", "iran"],
  ["is", "iceland", "island"],
  ["it", "italy", "italia"],
  ["jm", "jamaica"],
  ["jo", "jordan"],
  ["jp", "japan"],
  ["ke", "kenya"],
  ["kg", "kyrgyzstan", "kirgisistan"],
  ["kh", "cambodia", "kambodsja"],
  ["ki", "kiribati"],
  ["km", "comoros", "komorene"],
  ["kn", "saint kitts and nevis", "saint kitts og nevis", "saint kitts", "st kitts", "st kitts and nevis", "st kitts og nevis"],
  ["kp", "democratic people's republic of korea", "den demokratiske folkerepublikken korea", "north-korea", "north korea", "nord-korea", "nord korea"],
  ["kr", "republic of korea", "republikken korea", "south korea", "sør korea", "south-korea", "sør-korea"],
  ["kw", "kuwait"],
  ["kz", "kazakhstan", "kasakhstan"],
  ["la", "lao people's democratic republic", "den demokratiske folkerepublikken laos", "laos"],
  ["lb", "lebanon", "libanon"],
  ["lc", "saint lucia", "st lucia"],
  ["li", "liechtenstein"],
  ["lk", "sri lanka"],
  ["lr", "liberia"],
  ["ls", "lesotho"],
  ["lt", "lithuania", "litauen"],
  ["lu", "luxembourg", "luxemburg"],
  ["lv", "latvia"],
  ["ly", "libya"],
  ["ma", "morocco", "marokko"],
  ["mc", "monaco"],
  ["md", "republic of moldova", "republikken moldova", "moldova"],
  ["me", "montenegro"],
  ["mg", "madagascar", "madagaskar"],
  ["mh", "marshall islands", "marshalløyene"],
  ["mk", "former yugoslav republic of macedonia", "nord-makedonia", "nord makedonia", "north macedonia", "north-macedonia"],
  ["ml", "mali"],
  ["mm", "myanmar"],
  ["mn", "mongolia"],
  ["mr", "mauritania"],
  ["mt", "malta"],
  ["mu", "mauritius"],
  ["mv", "maldives", "maldivene"],
  ["mw", "malawi"],
  ["mx", "mexico"],
  ["my", "malaysia"],
  ["mz", "mozambique", "mosambik"],
  ["na", "namibia"],
  ["ne", "niger"],
  ["ng", "nigeria"],
  ["ni", "nicaragua"],
  ["nl", "netherlands", "nederland"],
  ["no", "norway", "norge"],
  ["np", "nepal"],
  ["nr", "nauru"],
  ["nz", "new zealand"],
  ["om", "oman"],
  ["pa", "panama"],
  ["pe", "peru"],
  ["pg", "papua new guinea", "papua ny-guinea", "papua ny guinea"],
  ["ph", "philippines", "filippinene"],
  ["pk", "pakistan"],
  ["pl", "poland", "polen"],
  ["pt", "portugal"],
  ["pw", "palau"],
  ["py", "paraguay"],
  ["qa", "qatar"],
  ["ro", "romania"],
  ["rs", "serbia"],
  ["ru", "russian federation", "russland", "russia"],
  ["rw", "rwanda"],
  ["sa", "saudi arabia"],
  ["sb", "solomon islands", "salomonøyene"],
  ["sc", "seychelles", "seychellene"],
  ["sd", "sudan"],
  ["se", "sweden", "sverige"],
  ["sg", "singapore"],
  ["si", "slovenia"],
  ["sk", "slovakia"],
  ["sl", "sierra leone"],
  ["sm", "san marino"],
  ["sn", "senegal"],
  ["so", "somalia"],
  ["sr", "suriname", "surinam"],
  ["ss", "south sudan", "sær-sudan", "sør sudan", "south-sudan"],
  ["st", "sao tome and principe", "sao tome og principe", "sao tome", "principe"],
  ["sv", "el salvador"],
  ["sy", "syrian arab republic", "syria"],
  ["sz", "eswatini", "swaziland"],
  ["td", "chad", "tsjad"],
  ["tg", "togo"],
  ["th", "thailand"],
  ["tj", "tajikistan", "tadsjikistan"],
  ["tl", "timor-leste", "øst-timor", "timor", "east-timor", "east timor", "øst timor"],
  ["tm", "turkmenistan"],
  ["tn", "tunisia"],
  ["to", "tonga"],
  ["tr", "turkey", "tyrkia"],
  ["tt", "trinidad and tobago", "trinidad og tobago", "trinidad", "tobago"],
  ["tv", "tuvalu"],
  ["tw", "republic of china", "republikken kina", "taiwan"],
  ["tz", "united republic of tanzania", "tanzania"],
  ["ua", "ukraine", "ukraina"],
  ["ug", "uganda"],
  ["us", "united states of america", "de forente amerikanske stater", "united states", "us", "usa"],
  ["uy", "uruguay"],
  ["uz", "uzbekistan", "usbekistan"],
  ["va", "vatican city state", "vatikanstaten", "vatican", "the vatican"],
  ["vc", "saint vincent and the grenadines", "saint vincent og grenadinene", "saint vincent", "st vincent"],
  ["ve", "bolivian republic of venezuela", "venezuela"],
  ["vn", "vietnam"],
  ["vu", "vanatu"],
  ["ws", "samoa"],
  ["xk", "kosovo"],
  ["ye", "yemen", "jemen"],
  ["za", "south africa", "sør-afrika", "sør afrika"],
  ["zm", "zambia"],
  ["zw", "zimbabwe"]

]
